#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         middleMotor,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         armMotor,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/* notes
*
* 90 degrees is north
*
*
*/
int currentX;
int currentY;
int angle = 180;
void moveRobot(float angleOfAttack){
	setMotorSpeed(leftMotor,sinDegrees(angleOfAttack)*50);
	setMotorSpeed(rightMotor,sinDegrees(angleOfAttack)*50);
	setMotorSpeed(middleMotor,cosDegrees(angleOfAttack)*50);
}
void goTo (float x, float y){
	int differentX = x-currentX;
	int differentY = y-currenty;
	float angleOAttack = radiansToDegrees(atan2(differentX, differentY));
	float distance = sqrt(  pow(differentX,2)  +  pow(differentY,2)  );
	displayTextLine(1,"%d", angleOAttack);
	displayTextLine(2,"%d", distance);
	moveRobot(-getGyroDegrees(port12)+angleOAttack);
	wait1Msec(distance * 1.4);
	currentX = x;
	currentY = y;
}
void setup(){


	goTo(1000,1000);
	goTo(0,0);

	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
	setMotorSpeed(middleMotor,0);

	/*
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);

	moveRobot(-getGyroDegrees(port12)+90);
	wait1Msec(1000);

	moveRobot(-getGyroDegrees(port12)+180);
	wait1Msec(1000);

	moveRobot(-getGyroDegrees(port12)+210);
	wait1Msec(1000);

	moveRobot(-getGyroDegrees(port12)+360);
	wait1Msec(1000);

	moveRobot(-getGyroDegrees(port12)+5609);
	wait1Msec(1000);

	moveRobot(-getGyroDegrees(port12)+2);
	wait1Msec(1000);
	/*
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);
	moveRobot(-getGyroDegrees(port12)+0);
	wait1Msec(1000);*/

}
void loops(){


}

task main()
{
	setup();
	while(true){
		loops();
	}
}
