#pragma config(Motor,  motor1,          Rlifter,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          Ltmotor,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          Rmotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          Llifter,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          Rtmotor,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         Lmotor,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goRight(int ms)
{
	int speed = 129;
	int speedRight = speed;
	int speedLeft = -speed;
	setMotorSpeed(Lmotor,speedLeft);
	setMotorSpeed(Rmotor,speedRight);
	setMotorSpeed(Ltmotor,speedLeft);
	setMotorSpeed(Rtmotor,speedRight);
	delay(ms);
}
void goLeft(int ms)
{
	int speed = 129;
	int speedRight = -speed;
	int speedLeft = speed;
	setMotorSpeed(Lmotor,speedLeft);
	setMotorSpeed(Rmotor,speedRight);
	setMotorSpeed(Ltmotor,speedLeft);
	setMotorSpeed(Rtmotor,speedRight);
	delay(ms);
}
void goForward(int ms)
{
	int speed = 129;
	int speedRight = speed;
	int speedLeft = speed;
	setMotorSpeed(Lmotor,speedLeft);
	setMotorSpeed(Rmotor,speedRight);
	setMotorSpeed(Ltmotor,speedLeft);
	setMotorSpeed(Rtmotor,speedRight);
	delay(ms);
}
void goBackward(int ms)
{
	int speed = 129;
	int speedRight = -speed;
	int speedLeft = -speed;
	setMotorSpeed(Lmotor,speedLeft);
	setMotorSpeed(Rmotor,speedRight);
	setMotorSpeed(Ltmotor,speedLeft);
	setMotorSpeed(Rtmotor,speedRight);
	delay(ms);
}
void goScoopUp(int deg)
{
	const int speed = -129;
	setMotorTarget(Llifter, -deg, speed);
	setMotorTarget(Rlifter, -deg, speed);
	waitUntilMotorStop(Llifter);
	waitUntilMotorStop(Rlifter);
}
void goScoopDown(int deg)
{
	const int speed = 129;
	setMotorTarget(Llifter, deg, speed);
	setMotorTarget(Rlifter, deg, speed);
	waitUntilMotorStop(Llifter);
	waitUntilMotorStop(Rlifter);
}
void goDump()
{
	goScoopUp(1300);
	setMotorSpeed(Lmotor, 0);
	setMotorSpeed(Rmotor, 0);
	setMotorSpeed(Ltmotor, 0);
	setMotorSpeed(Rtmotor, 0);
	delay(500);
	goScoopDown(0);
	resetMotorEncoder(Llifter);
	resetMotorEncoder(Rlifter);
}

void anthony()
{
	goRight(630);
	goForward(3000);
	goBackward(1500);
	goLeft(900);
	goForward(3000);
	goBackward(100);
	goScoopUp(500);
	goLeft(530);
	goBackward(1300);
	goLeft(430);
	goBackward(800);
	goBackward(0);
	goDump();
}
void michael()
{
	goForward(500);
	goLeft(150);
	goForward(4200);
	goBackward(1500);
	goRight(1100);
	goForward(3500);
	goBackward(100);
	goScoopUp(500);
	goRight(530);
	goBackward(1300);
	goRight(430);
	goBackward(800);
	goBackward(0);
	goDump();
}

task main()
{
	anthony();
	michael();
}
